config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :work
  resources :photos

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :photos
	has_attached_file :photo
end

app/models/work.rb
class Work < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  respond_to :json, :html

  # GET /places
  # GET /places.json
  def index
   #@place = Place.all

 
  
  end

  def yelp_search
    @yelp = Yelp.client.search(params[:location], { term: params[:business] })
    respond_with @yelp
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :address, :desc)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :setup, :edit, :update, :destroy]
  # validate_presence_of :email, :format { regex }

  respond_to :json, :html

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  def grab
    @resp = User.all
    respond_with @resp
  end

  def user_search
    @resp = User.where("fb_id = '#{params[:fb_id]}'").first
    respond_with @resp
  end



  def yelp_search
    @yelp = Yelp.client.search(params[:location], { term: params[:business] })
    respond_with @yelp
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @users = User.find(params[:id])

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/setup
  def setup
  end

  # GET /users/1/edit
  def edit
  
end
  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        # format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, avatar: @user }
        #format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
     # @photo = User.find(user_params[:avatar_file_name])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :age, :avatar, :avatar_file_name, :gender, :rel_type, :location, :radius, :fb_id, :orientation)
    end 
end

app/controllers/work_controller.rb
class WorkController < ApplicationController
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/work_helper.rb
module WorkHelper
end

app/views/layouts/_nav.html.erb
<header role="banner">

<nav id="navbar-primary" class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-primary-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
    <!-- Search box -->
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <!-- / Search box -->
      <ul class="nav navbar-nav navbar-left">
          <% if @user != nil %>
            <li> <%#= link_to "Home", show_user_path %></li>
            <li> <%= link_to "Edit Profile", users_path %> </li>
            <li> <%= link_to "My Match", matches_path %> </li>
            <li> <%= link_to "Mine", match_events_path %> </li>
            <li> <%= link_to "Find Places", places_path %> </li>
            <li> <%= link_to "Match Event", photos_path %> </li>
            <div class = "user", "matches", "events" ></div>
      <% else %>
            <li> <%= link_to "Log In", new_user_path, method: :get %></li>
      <% end %>
      
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Toolbox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/places/index.html.erb
<script>
// Make sure our code runs after the page is fully rendered
  $(function(){
    // Go grab places names in an array
    $.get("/places.json", function(places){
      // Set up the autocomplete
      $( "#tags" ).autocomplete({
        // Have the source be the incoming places array
        source: places
      });
    });
  });
</script>

<form class="test" id="test1">
  <input type="text" id="yelp_loc" placeholder="Search Area"><br><br>
  <input type="text" id="yelp_bus1" placeholder="Favorite Location">
  <input class="button" id="button1" type="submit" value="Submit" >
</form>
<br><br>
<form class="hidden test" id="test2">
  <input type="text" id="yelp_bus2" placeholder="Second Favorite Location">
  <input class="button" id="button2" type="submit" value="Submit" >
  <div class="tip" id="yelp_bus2" style="margin-left:100px;">
</form>
<br><br>
<form class="hidden test" id="test3">
  <input type="text" id="yelp_bus3" placeholder="Third Favorite Location">
  <input class="button" id="button3" type="submit" value="Submit" >
</form>

app/views/user_place_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Place Categories</h1>

<table>
  <thead>
    <tr>
      <th>Userplace</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_place_categories.each do |user_place_category| %>
      <tr>
        <td><%= user_place_category.userplace_id %></td>
        <td><%= user_place_category.category %></td>
        <td><%= link_to 'Show', user_place_category %></td>
        <td><%= link_to 'Edit', edit_user_place_category_path(user_place_category) %></td>
        <td><%= link_to 'Destroy', user_place_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<br>

<%= link_to 'New User place category', new_user_place_category_path %>

app/views/users/_form.html.erb
  <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 60px;
      }

      /* Custom container */
      .container {
        margin: 0 auto;
        max-width: 1000px;
      }
      .container > hr {
        margin: 60px 0;
      }

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 80px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 100px;
        line-height: 1;
      }
      .jumbotron .lead {
        font-size: 24px;
        line-height: 1.25;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

      /* Supporting marketing content */
      .marketing {
        margin: 60px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }


      /* Customize the navbar links to be fill the entire space of the .navbar */
      .navbar .navbar-inner {
        padding: 0;
      }
      .navbar .nav {
        margin: 0;
        display: table;
        width: 100%;
      }
      .navbar .nav li {
        display: table-cell;
        width: 1%;
        float: none;
      }
      .navbar .nav li a {
        font-weight: bold;
        text-align: center;
        border-left: 1px solid rgba(255,255,255,.75);
        border-right: 1px solid rgba(0,0,0,.1);
      }
      .navbar .nav li:first-child a {
        border-left: 0;
        border-radius: 3px 0 0 3px;
      }
      .navbar .nav li:last-child a {
        border-right: 0;
        border-radius: 0 3px 3px 0;
      }
    </style>

 <div class="container">

 <div class="masthead">
        <h3 class="muted">Project name</h3>
        <div class="navbar">
          <div class="navbar-inner">
            <div class="container">
              <ul class="nav">
                <li class="active"><a href="#">Home</a><%= form_for(@user) do |f| %>
  <% if @user.errors.any? %></li>
                <li><a href="#">Projects</a></li>
                <li><a href="#">Services</a></li>
                
              </ul>
            </div>
          </div>
        </div><!-- /.navbar -->

  <ul class="nav nav-tabs">
    <li class="active"><a href="#Home" data-toggle="tab">Home</a></li>
    <li><a href="Show" data-toggle="tab">About</a></li>
    <li><a href="actions" data-toggle="tab">Actions</a></li>
  </ul>
      </div>



  



    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_field :password_digest %>
  </div>
  <p>
  <strong>image:</strong>
  <%= image_tag @user.photo.url %>
</p>
  <div class="actions">
    <%= f.submit %>
  </div>




<% end %>

app/views/users/edit.html.erb
<div class="container">
<h1>Editing User</h1>
</div>
<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
<%= link_to 'Work Done', work_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<h1>Listing Users</h1>
</div>

<div class="container">

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
</div>

app/views/users/new.html.erb
<div class="container">

<table>
  <thead>
      <tr>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
      </tr>
  </thead>

</table>
<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new2.html.erb
<h1>New User</h1>

<head>
<title>Facebook Login JavaScript Example</title>
<meta charset="UTF-8">
</head>
<body>
<script>
  // This is called with the results from from FB.getLoginStatus().
  function statusChangeCallback(response) {
    console.log('statusChangeCallback');
    console.log(response);
    // The response object is returned with a status field that lets the
    // app know the current login status of the person.
    // Full docs on the response object can be found in the documentation
    // for FB.getLoginStatus().
    if (response.status === 'connected') {
      // Logged into your app and Facebook.
      testAPI();
      // posttodatabase();
    } else if (response.status === 'not_authorized') {
      // The person is logged into Facebook, but not your app.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into this app.';
    } else {
      // The person is not logged into Facebook, so we're not sure if
      // they are logged into this app or not.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into Facebook.';
    }
  }

  // This function is called when someone finishes with the Login
  // Button.  See the onlogin handler attached to it in the sample
  // code below.
  function checkLoginState() {
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
  }

  window.fbAsyncInit = function() {
  FB.init({
    appId      : '415436648618689',
    cookie     : true,  // enable cookies to allow the server to access 
                        // the session
    xfbml      : true,  // parse social plugins on this page
    version    : 'v2.2' // use version 2.2
  });

  // Now that we've initialized the JavaScript SDK, we call 
  // FB.getLoginStatus().  This function gets the state of the
  // person visiting this page and can return one of three states to
  // the callback you provide.  They can be:
  //
  // 1. Logged into your app ('connected')
  // 2. Logged into Facebook, but not your app ('not_authorized')
  // 3. Not logged into Facebook and can't tell if they are logged into
  //    your app or not.
  //
  // These three cases are handled in the callback function.

  FB.getLoginStatus(function(response) {
    statusChangeCallback(response);
  });

  };

  // Load the SDK asynchronously
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));


  FB.login(function(response) {
    // Original FB.login code
  }, { auth_type: 'reauthenticate' })

  // Here we run a very simple test of the Graph API after login is
  // successful.  See statusChangeCallback() for when this call is made.
  function testAPI() {
    console.log('Welcome!  Fetching your information.... ');
    FB.api('/me', function(response) {
      console.log('Successful login for: ' + response.name);
      console.log(response)
      console.log("response email: " + response.email)
      document.getElementById('status').innerHTML =
        'Thanks for logging in, ' + response.name + '!';
        // function posttodatabase(response){
          $.ajaxSettings.dataType = "json";
            // $(document).ready(function(){  
                  $.ajax({
                  type: "POST",
                  url: "/users",
                  dataType: "json",
                  data: { user: { name: response.name, gender: response.gender, age: response.age, email: (response.email && response.email.length > 0) ? response.email  : "null@email.com" } },
                  success: function(response){
                    console.log("sucess")
                  },
                  error: function(e){
                    console.log("error")
                    console.log(e)
                  }
                // })
            })
        // }   
    }
  // }




    //    FB.logout(function(response){
    //     // Person is now logged out
    // })
)}
</script>

<!--
  Below we include the Login Button social plugin. This button uses
  the JavaScript SDK to present a graphical Login button that triggers
  the FB.login() function when clicked.
-->
<!-- <fb:login-button scope="public_profile,email" onlogin="checkLoginState();">
</fb:login-button>
 -->
<fb:login-button autologoutlink="true" size="large" show-face="true"></fb:login-button>

<div id="status">
</div>

<%= link_to "Log in with Facebook", "/auth/facebook" %>

</body>

<!-- <= render 'form' %>
 -->
<!-- <= link_to 'Back', users_path %>
 -->

app/views/users/show.html.erb
<div class="container">
<h1>Show User</h1>
</div>
<%= render 'form' %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/work/index.html.erb
<div class="container">
<h1>work done</h1>
</div>

app/views/work/show.html.erb
<div class="container">
<h1>show what work is done</h1>
</div>